### ISSUE TITLE
No milestone selected in PR check

### ISSUE THREAD

**Issue by zoispag** [jusx/mergeable#111]
Looking at the full config in readme, it looks like there is no way to request for `no_empty` for a PR's milestone like we can do for the description.

I was able to replicate the behaviour using regex, using the following config:

```yml
mergeable:
  pull_requests:
    milestone:
      must_include:
        regex: '([^\s]*)'
        message: 'This PR cannot be merge unless it belongs to a milestone.'
```

Should it be added though?

**Comment by jusx** [comment]
@zoispag I think we can add a `no_empty` property for milestone as a convenience and perhaps consistency.

**Comment by zoispag** [comment]
@jusx that would be great. Thanks

**Comment by jusx** [comment]
`no_empty` has been added to the `milestone` validator in flex and was deployed a few days ago:

```yml
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: milestone
        no_empty:
          enabled: true
```
Do note that if the body of PR includes a [GH keyword referencing an issue](https://help.github.com/articles/closing-issues-using-keywords/) that has a milestone associated to it, mergeable will see it as valid. Milestone in this case is not empty. 

Closing this issue as I have verified that this is working :-)
