### ISSUE TITLE
No check is triggered when a milestone is changed in an open PR

### ISSUE THREAD

**Issue by zoispag** [jusx/mergeable#113]
I have added check for milestone in PRs in my config.
When I create a PR, if I forget to add milestone, the mergeable will mark it as failed.
If I add the PR in a milestone, the mergeable check remains `red`.
I have to re-trigger a check by changing the title, the description or the labels.

By the way, re-run via Checks tab does not seem to be running.

![image](https://user-images.githubusercontent.com/21138205/49395393-9c74e000-f736-11e8-841f-6172092ff06f.png)

**Comment by jusx** [comment]
@zoispag I can't reproduce this. Question: Did you install the Mergeable GitHub App as [found here](https://github.com/apps/mergeable) or are you using your own instance?

If it's the later it may be a GitHub App Settings issue.

Also yes, the re-run via Checks currently does not work. We have not implemented it yet.

**Comment by zoispag** [comment]
@jusx No, i am using the app directly as found in the link you sent. Not using own instance.

It is still happening. Mergeable is not triggered by Milestone changing in a PR. Something else you would like from me to try?

**Comment by jusx** [comment]
@zoispag That's really odd. Here's a screencast of my attempt to reproduce the problem:

![mergeable-milestone](https://user-images.githubusercontent.com/359064/49928332-cdf75500-fe74-11e8-931e-a35fa8597387.gif)

As you can see, mergeable is triggered each time. 

If you don't mind, may I see your yml config?

**Comment by zoispag** [comment]
Sure @jusx.

```yml
mergeable:
  pull_requests:
    stale:
      days: 20
      message: 'This PR is stale. Please follow up!'

    title:
      must_exclude:
        regex: 'wip|dnm'
        message: 'This PR is work in progress.'

    label:
      must_exclude:
        regex: 'Do not merge'
        message: 'This PR is work in progress.'

    description:
      no_empty:
        enabled: false
        message: 'PR description is required'

    milestone:
      must_include:
        regex: '([^\s]*)'
        message: 'This PR cannot be merged if does not belong to a milestone.'
```
