### ISSUE TITLE
This PR is stale comment for all Issues today!

### ISSUE THREAD

**Issue by zoispag** [jusx/mergeable#148]
We are receiving a “This PR is stable comment” in all Issues today! I guess started since the latest commits today! It is spamming us and there are around 200 issues open which are receiving comment. Please take a look

**Comment by jusx** [comment]
@zoispag Apologies! It seems there might be a problem with the `[stale](https://github.com/jusx/mergeable#stale)` option. We've just deployed a new version with new configuration formats and currently do a transform of the old configuration formats to the new one for backward compatibility. 

There may be a use case we missed. Do you mind attaching your mergeable configuration for that repository? It will help us find the root of the problem. A screenshot of the comment will be useful as well.

Apologies again! And thanks so much for your patience.

**Comment by zoispag** [comment]
@jusx no worries. It happens!

```yml
mergeable:
  pull_requests:
    stale:
      # number of days for a PR to be considered stale. A comment is posted when it is stale.
      days: 20
      # Optional property. When not specified the default is used. The default message is:
      # There haven't been much activity here. This is stale. Is it still relevant? This is a friendly reminder to please resolve it. :-)
      message: 'This PR is stale. Please follow up!'

    # Regular expression to be tested on the title. Not mergeable when true.
    title:
      must_exclude:
        regex: 'wip|dnm'
        message: 'This PR is work in progress.'

    # Match text against labels. Not mergeable when true.
    label:
      must_exclude:
        regex: 'Do not merge'
        message: 'This PR is work in progress.'

    description:
      no_empty:
        enabled: false
        message: 'PR description is required'

    milestone: '([^\s]*)'
```
