### ISSUE TITLE
Easily enforce consistency in title

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#15]
Make it easy to configure mergeable such that the title follows a certain format. For example, in previous projects we've required certain prefixes like `(feat)`, `(doc)`, `(fix)` in the title. This should be easily configured without complex regex like this https://github.com/jusx/mergeable/issues/12#issuecomment-386956281

Instead we should be able to do something like this:

```yml
title: 
   excludes: 'wip'
   includes: '^\(feat\)|^\(doc\)|^\(fix\)' 
```

Probably will still want to be backward compatible with:
```yml
title: 'wip'
```
