### ISSUE TITLE
Title `begins_with` is not working as intended

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#158]
`begins_with` does not seem to be validating properly.

### To Reproduce
1. Create a recipe like this:
```yml

version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        begins_with:
          match: 'feat', 'bug'
          message: 'Type is required....'
```

2. Set the title of the PR to be "Something that does not match"

#### Actual
The PR is still mergeable. Result is `pass`.

#### Expected: 
PR should not be mergeable. Result should be `fail`.

**Comment by jusx** [comment]
In the mean time using the following will work and does the same thing:

```
version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: ^(feat|bug)
          message: 'Type is required...'
``

**Comment by shine2lay** [comment]
i got this error when i tested the config you posted above

![image](https://user-images.githubusercontent.com/5243508/51790761-3f057a00-214e-11e9-80a6-c3f86456c141.png)

**Comment by shine2lay** [comment]
@jusx took a closer look, we are also not accepting an array for `match` sub option it can only be a string

**Comment by jusx** [comment]
From the documentation, mergeable is supposed to support a comma delimited list of strings:

```yml
begins_with:
     match: 'doc','feat','fix','chore'  
     message: 'Some message...'
  ends_with:
     match: 'A String' # or comma delimited list of strings
     message: 'Come message...'
     # all of the message sub-option is optional   
```

Ideally the above works. Array values like `[feat, core]` or `['feat', 'core'] are also valid array string values in [js-yaml](https://github.com/nodeca/js-yaml), those should work. However, they currently do not because there are logic errors in the options:

https://github.com/jusx/mergeable/blob/d7a7d90694afb0b7e868792be135a0c6d090f848/lib/validators/options_processor/options/begins_with.js#L19

When it's a `title` validator it's then checking if the title is a `string` -- which it always will be. Else:

https://github.com/jusx/mergeable/blob/d7a7d90694afb0b7e868792be135a0c6d090f848/lib/validators/options_processor/options/begins_with.js#L21

The above will never be true since in this case, title is always only ever a string. It should be inspecting the `match` sub-option value.

Lastly in the test:
https://github.com/jusx/mergeable/blob/d7a7d90694afb0b7e868792be135a0c6d090f848/__tests__/validators/options_processor/options/begins_with.test.js#L24

Since `input` is supposed to be the value from the payload, the above should be setting up the values in the configuration:
```js
rule = {begins_with: { match: ['A', 'B', 'the test'] }}
```

The same problem exists in `ends_with`
