### ISSUE TITLE
Checks does not complete when specifying approvals with OR in the configuration

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#171]
## To Reproduce
1. Create a recipe like this:

```yml
version: 2
mergeable:
  - when: pull_request.open, pull_request_review.*
    validate:
      - do: approvals
        or:
          - required:
              reviewers: ['jusx']
          - required:
              reviewers: ['shine2lay']
```

2. Open a PR.

### Actual
The Mergeable check in the PR stays at pending indefinitely.

### Expected
The Mergeable check should validate and complete appropriately.

## Notes
- This problem exists only for **private** repos because as a GH App, Mergeable does not request for read permissions to the repo content. It is failing abruptly when trying to read the OWNERS file and receives the error "Resource not accessible by integration."

- For this particular recipe, it should not be requesting for owners file. That should only be done, when the `owner` option is used.
