### ISSUE TITLE
Checks when specifying OR approvals in the config doesn't seem to consider all approvers.

### ISSUE THREAD

**Issue by brianzhou13** [jusx/mergeable#174]
## To Reproduce
1. Create a recipe similar like this:
**copied from https://github.com/jusx/mergeable/issues/171**
```yaml
version: 2
mergeable:
  - when: pull_request.open, pull_request_review.*
    validate:
      - do: approvals
        or:
          - required:
              reviewers: ['user_one']
          - required:
              reviewers: ['user_two']
```

1. Open a PR.
2. Have 3 approvers, 2 within the or statements ("user_one" and "user_two") and 1 ("user_three") that isn't.

### Actual
The Mergeable check in the PR only considers the 1 that isn't on the list.

### Expected
The Mergeable check should consider all 3 and approve.

## Notes
This issue is occurring in a private repo
