### ISSUE TITLE
Require a list of Reviewers

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#25]
Validate that a user or list of users have reviewed the pull request in order for it to be mergeable.

Reviewer list should be configurable in the YAML with:

```yml
  approvals:
    required:
      reviewers: [ user1, user2 ]   # list of gh usernames
      message: 'Custom message...'
```

or 

```yml
  approvals:
    required: [ user1, user2 ] 
```
