### ISSUE TITLE
Validate min and max of Asignee in PR

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#29]
## Context
A team may decide that every PR should have at least an assignee. By default zero number of assignees is acceptable.

## Details
Support Advanced settings:
```
  assignee:
    min: 1
    max: 1
    message: 'Custom message...'
```

and simple:

```
assignee: 1 # min number of assignees.
```
