### ISSUE TITLE
Validate TODOs in PR

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#34]
## Context

Some PRs may have a TODO list (list of checkboxes). Typically an Engineer may have this as a checklist for all that needs to be done while PR is in WIP.

## Solution

Should be mergeable if not all the checkboxes are checked. 

Simple configuration:
```yml
todo: true
```
Advanced:
```yml
todo: 
   enabled: true
   message: 'a custom message'
```

**Comment by shine2lay** [comment]
@udaiveerS are you working on this issue?

**Comment by udaiveerS** [comment]
I am not working on it. It preety straight forward, but I guess node is still a lil confusing. If you  guys want to fnish ASAP that is fine.

**Comment by shine2lay** [comment]
@udaiveerS we are not in a hurry, if you are planning to take on this issue, i was going to label it `in-progress` to avoid duplicate work

**Comment by jusx** [comment]
Closing this issue because this is already possible with the following recipe:

```
version 2
mergeable:
  when: pull_request.*
  - do: description
    must_exclude:
      regex: '\[ \]'
      message: All todos must be completed before merging.
```
