### ISSUE TITLE
Validate dependent files in PR

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#36]
## Context

There are instances where there are dependent files. For example when a project is using yarn but yarn.lock is not necessarily automatically generated but is required to be committed for deployment to various env. to work.

## Solution

Validate that modified files includes all configured dependent file list. 

Advanced configuration:
```yml
dependent:
   files:
      - 'package.json'
      - 'yarn.lock'
   message: 'custom message' # this is optional.
```
