### ISSUE TITLE
Warn Against Stale PRs

### ISSUE THREAD

**Issue by jusx** [jusx/mergeable#39]
## Context

In large repos (usually a monolith) with many contributors the number of PRs can be long. Some PRs become stale and eventually is no longer up to date. 

## Solution
Prompt the author when a PR stays open for `n` number of days.

Configuration:

```
workflow:
   stale:
      pull_request: 
         days: 20 # number of days.
         message: 'some message' # custom message. 
```
