### ISSUE TITLE
Check copyright and license notices

### ISSUE THREAD

**Issue by kivutar** [jusx/mergeable#53]
Some projects require that every source file starts with a piece of text related to license and copyright.

The CI could block a PR if some new files are introduced without these lines.

**Comment by jusx** [comment]
@shine2lay You are correct. Need to think through what the right construct is for the configuration... let me give this some thought.

**Comment by shine2lay** [comment]
how about 
```
pull_requests:
   check_file:
      # Check each modified file in the PR for the following starting at line 0.
      header: > 
           Entire license header.
      # only enforce it for these file patterns
      files: *.go
```

because i can imagine, there could also be other sub_options like `footer` and `contains`

**Comment by jusx** [comment]
I think that `files` as the subject would be good enough because they are all checks.

Also considering the other objects as you say. We should consider custom messages for each:

```yml
files:
   header: >
   Bla bla bla lorem ipsum.
   more stuff.
      
    pattern: *.go
    message: 'a custom message about this error'

  other:
    pattern: *.js
    message: 'other message'
```
