### ISSUE TITLE
It freezes in 'Mergeable Tests running' state

### ISSUE THREAD

**Issue by Najki** [jusx/mergeable#71]
I've installed Mergeable in my fresh private repository which also has two Jenkins builds attached using Webhooks. Here is my work in progress `.github/mergeable.yml`:

```yml
# https://github.com/jusx/mergeable
mergeable:
    pull_requests:
        # Minimum of 5 approvals is needed.
        approvals: 1

        stale:
            # number of days for a PR to be considered stale. A comment is posted when it is stale.
            days: 20

            # Optional property. When not specified the default is used. The default message is:
            # There haven't been much activity here. This is stale. Is it still relevant? This is a friendly reminder to please resolve it. :-)
            message: 'This is PR is stale. Please follow up!'

        title:
            must_exclude:
                regex: 'wip'
                message: 'This PR is work in progress.'

            begins_with:
                match: '(FEAT\-)|(BF\-)'
                message: 'PR title should start with FEAT- or BF-'

        description:
            no_empty:
                enabled: true
                message: 'PR requires a description'

```

After creating my first PR, 3 checks show up - two Jenkins checks (as expected) and Mergeable check. The Mergeable check has the "Mergeable Tests running" state. Jenkins build finish successfully but Mergeable stays in "Tests running" state. I've made some errors in the PR which should be caught by Mergeable, just to test if it's working but nothing happens.

It has been like this for the last 3 hours. Will it finish eventually?
