### ISSUE TITLE
Title contains **export** does not pass mergeable

### ISSUE THREAD

**Issue by knd** [jusx/mergeable#97]
Title contains **export** does not pass mergeable because it contains substring **exp**.

**Comment by shine2lay** [comment]
@knd I believe this is because in default config, title can't contain "wip|dnm|exp|poc". we use regex to check it against the titile. since `exp` was there in `export` it failed! Thanks for the feedback, we should check it to match `exp` word specifically

**Comment by knd** [comment]
we could introduce different syntax like: [wip], [dmm], [exp]

anything with brackets, square brackets, or @ sign prepended. That would work around the issue.

**Comment by jusx** [comment]
@knd I believe the problem is primarily that the default assumes this is the settings people want. We will remove these defaults in the future. In the meantime the workaround is to configure it differently in your repos mergeable settings.

**Comment by anathefish** [comment]
hey ppl, looks like there is no possibilities to configure it in mergeable settings.The defaults stay whatever is under 'title' setting. Currently any words that contain wip|dnm|exp|poc gonna fail the check.

**Comment by jusx** [comment]
@anathefish You can configure the regex of `title` as documented here https://github.com/jusx/mergeable#configuration

Does it not work for you?

**Comment by jusx** [comment]
@knd We plan on removing the defaults. In the meantime you can override it by creating `.github/mergeable.yml`. Here's an example recipe:

```yml
version: 2
mergeable:
  - when: pull_request.*
    validate:
      - do: title
        # Do not merge when WIP is found.
        must_exclude:
          regex: ^\[WIP\]
        # Adhere to semantic-release convention.
        must_include: 
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$            
      # Do not merge when WIP.        
      - do: label
        must_exclude:
          regex: 'wip'
 ```

Closing this issue since it's a matter of configuration.
