### ISSUE TITLE
Title: must_include: regex fails with "TypeError: Cannot read property 'trim' of null"

### ISSUE THREAD

**Issue by kevnm67** [jusx/mergeable#98]
When trying to validate pull request titles, mergeable fails with the following:

![image](https://user-images.githubusercontent.com/2734154/46024254-60792b00-c0b4-11e8-8c9b-1589578fc84d.png)

I've tried using the example from the readme:

```
title:
  must_include:
    regex: `^\\(feat\\)|^\\(doc\\)|^\\(fix\\)`
      message: `Title must have prefixes for the following: (feat), (doc), (fix)`
```

and the following:

```
  must_include:
    regex: `#\d{7,}'
```

**Comment by shine2lay** [comment]
@kevnm67 hey! sorry for the late response. I wasn't able to reproduce this specific bug at all, I've checked the code base for possible scenarios and i've tested them, it doesn't seem to occur to me. 
@jusx do you have any clue what might cause this bug?
@kevnm67 Could you please provide the full `mergeable.yml`, value you had for `title` and `description`? Thanks

**Comment by shine2lay** [comment]
@kevnm67 I used your settings, i didn't get the same bug as you did. 
You can check the test PRs i made [https://github.com/shine2lay/Test/pull/44](here) and [https://github.com/shine2lay/Test/pull/40](here).

Nevertheless, I did notice a few things: 
- the regex in our README.md is not working properly, this one `^\\(feat\\)|^\\(doc\\)|^\\(fix\\)`. it should be `^\(feat\)|^\(doc\)|^\(fix\)`. (i'll create a seperate issue for this) 
- I noticed you are using `begins_with` with `regex` sub_option, please notice in our readme that it is only accepting `match` sub_option 
- I maybe wrong, i think the following is the regex expression that fits your requirements better. `^\[(Delivers \#\d{7,}|Finishes \#\d{7,}|\#\d{7,})\]` . this will enforce `#7digits` after `Delivers or Finishes` or `#7digits` by itself. 
- please try the following setting which i've used to test the two PR above 
```
mergeable:
  pull_requests:
    stale:
      days: 14
      message: "This is PR is stale. Please follow up!"
    title:
      must_include:
        message: 'Title must include a pivotal story tag and optionally an action (e.g. Delivers or Finishes)'
        regex: ^\[(Delivers \#\d{7,}|Finishes \#\d{7,}|\#\d{7,})\]
```
